language: node_js
node_js:
  - 10
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run-script build
branches:
  only:
  - development
git:
  quiet: true
  submodules: false
